//! Every ArbOS precompile method as Nitro defines it, generated from Nitro's
//! `precompiles/precompile.go` (`arbosVersion` / `maxArbosVersion` assignments, the per-precompile
//! versions and the `stylusMethods` list) and the ABI at nitro-precompile-interfaces 7e88c8c
//! (selectors and `stateMutability`). Regenerate it when the Nitro pin moves.

use super::{ArbPrecompilesEnum as E, MethodPurity as M};

/// `(precompile, method, selector, precompile's own ArbOS version, method min ArbOS version,
/// method max ArbOS version (0 = none), mutability)`.
pub(super) type NitroMethod = (E, &'static str, [u8; 4], u64, u64, u64, M);

pub(super) const NITRO_METHODS: &[NitroMethod] = &[
    (
        E::ArbAddressTable,
        "addressExists",
        [0xa5, 0x02, 0x52, 0x22],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbAddressTable,
        "compress",
        [0xf6, 0xa4, 0x55, 0xa2],
        0,
        0,
        0,
        M::Write,
    ),
    (
        E::ArbAddressTable,
        "decompress",
        [0x31, 0x86, 0x2a, 0xda],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbAddressTable,
        "lookup",
        [0xd4, 0xb6, 0xb5, 0xda],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbAddressTable,
        "lookupIndex",
        [0x8a, 0x18, 0x67, 0x88],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbAddressTable,
        "register",
        [0x44, 0x20, 0xe4, 0x86],
        0,
        0,
        0,
        M::Write,
    ),
    (
        E::ArbAddressTable,
        "size",
        [0x94, 0x9d, 0x22, 0x5d],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbAggregator,
        "addBatchPoster",
        [0xdf, 0x41, 0xe1, 0xe2],
        0,
        0,
        0,
        M::Write,
    ),
    (
        E::ArbAggregator,
        "getBatchPosters",
        [0xe1, 0x05, 0x73, 0xa3],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbAggregator,
        "getDefaultAggregator",
        [0x87, 0x58, 0x83, 0xf2],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbAggregator,
        "getFeeCollector",
        [0x9c, 0x2c, 0x5b, 0xb5],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbAggregator,
        "getPreferredAggregator",
        [0x52, 0xf1, 0x07, 0x40],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbAggregator,
        "getTxBaseFee",
        [0x04, 0x97, 0x64, 0xaf],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbAggregator,
        "setFeeCollector",
        [0x29, 0x14, 0x97, 0x99],
        0,
        0,
        0,
        M::Write,
    ),
    (
        E::ArbAggregator,
        "setTxBaseFee",
        [0x5b, 0xe6, 0x88, 0x8b],
        0,
        0,
        0,
        M::Write,
    ),
    (
        E::ArbDebug,
        "becomeChainOwner",
        [0x0e, 0x5b, 0xbc, 0x11],
        0,
        0,
        0,
        M::Write,
    ),
    (
        E::ArbDebug,
        "customRevert",
        [0x7e, 0xa8, 0x9f, 0x8b],
        0,
        0,
        0,
        M::Pure,
    ),
    (
        E::ArbDebug,
        "events",
        [0x7b, 0x99, 0x63, 0xef],
        0,
        0,
        0,
        M::Payable,
    ),
    (
        E::ArbDebug,
        "eventsView",
        [0x8e, 0x5f, 0x30, 0xab],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbDebug,
        "legacyError",
        [0x1e, 0x48, 0xfe, 0x82],
        0,
        0,
        0,
        M::Pure,
    ),
    (
        E::ArbDebug,
        "overwriteContractCode",
        [0x1b, 0xe2, 0x50, 0xd6],
        0,
        0,
        0,
        M::Write,
    ),
    (
        E::ArbDebug,
        "panic",
        [0x47, 0x00, 0xd3, 0x05],
        0,
        30,
        0,
        M::Write,
    ),
    (
        E::ArbFilteredTransactionsManager,
        "addFilteredTransaction",
        [0xcb, 0x47, 0x04, 0x91],
        60,
        60,
        0,
        M::Write,
    ),
    (
        E::ArbFilteredTransactionsManager,
        "deleteFilteredTransaction",
        [0xd2, 0x63, 0x74, 0xb1],
        60,
        60,
        0,
        M::Write,
    ),
    (
        E::ArbFilteredTransactionsManager,
        "isTransactionFiltered",
        [0x85, 0xc7, 0x33, 0xa4],
        60,
        60,
        0,
        M::View,
    ),
    (
        E::ArbFunctionTable,
        "get",
        [0xb4, 0x64, 0x63, 0x1b],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbFunctionTable,
        "size",
        [0x88, 0x98, 0x70, 0x68],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbFunctionTable,
        "upload",
        [0xce, 0x2a, 0xe1, 0x59],
        0,
        0,
        0,
        M::Write,
    ),
    (
        E::ArbGasInfo,
        "getAmortizedCostCapBips",
        [0x7a, 0x7d, 0x6b, 0xeb],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbGasInfo,
        "getCurrentTxL1GasFees",
        [0xc6, 0xf7, 0xde, 0x0e],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbGasInfo,
        "getGasAccountingParams",
        [0x61, 0x2a, 0xf1, 0x78],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbGasInfo,
        "getGasBacklog",
        [0x1d, 0x5b, 0x5c, 0x20],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbGasInfo,
        "getGasBacklogTolerance",
        [0x25, 0x75, 0x4f, 0x91],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbGasInfo,
        "getGasPricingConstraints",
        [0x23, 0x20, 0x27, 0xd1],
        0,
        50,
        0,
        M::View,
    ),
    (
        E::ArbGasInfo,
        "getL1BaseFeeEstimate",
        [0xf5, 0xd6, 0xde, 0xd7],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbGasInfo,
        "getL1BaseFeeEstimateInertia",
        [0x29, 0xeb, 0x31, 0xee],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbGasInfo,
        "getL1FeesAvailable",
        [0x5b, 0x39, 0xd2, 0x3c],
        0,
        10,
        0,
        M::View,
    ),
    (
        E::ArbGasInfo,
        "getL1GasPriceEstimate",
        [0x05, 0x5f, 0x36, 0x2f],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbGasInfo,
        "getL1PricingEquilibrationUnits",
        [0xad, 0x26, 0xce, 0x90],
        0,
        20,
        0,
        M::View,
    ),
    (
        E::ArbGasInfo,
        "getL1PricingFundsDueForRewards",
        [0x96, 0x3d, 0x60, 0x02],
        0,
        20,
        0,
        M::View,
    ),
    (
        E::ArbGasInfo,
        "getL1PricingSurplus",
        [0x52, 0x0a, 0xcd, 0xd7],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbGasInfo,
        "getL1PricingUnitsSinceUpdate",
        [0xef, 0xf0, 0x13, 0x06],
        0,
        20,
        0,
        M::View,
    ),
    (
        E::ArbGasInfo,
        "getL1RewardRate",
        [0x8a, 0x5b, 0x1d, 0x28],
        0,
        11,
        0,
        M::View,
    ),
    (
        E::ArbGasInfo,
        "getL1RewardRecipient",
        [0x9e, 0x6d, 0x7e, 0x31],
        0,
        11,
        0,
        M::View,
    ),
    (
        E::ArbGasInfo,
        "getLastL1PricingSurplus",
        [0x29, 0x87, 0xd0, 0x27],
        0,
        20,
        0,
        M::View,
    ),
    (
        E::ArbGasInfo,
        "getLastL1PricingUpdateTime",
        [0x13, 0x8b, 0x47, 0xb4],
        0,
        20,
        0,
        M::View,
    ),
    (
        E::ArbGasInfo,
        "getMaxBlockGasLimit",
        [0x03, 0x71, 0xfd, 0xb4],
        0,
        50,
        0,
        M::View,
    ),
    (
        E::ArbGasInfo,
        "getMaxTxGasLimit",
        [0xaa, 0xe1, 0xcd, 0x4c],
        0,
        50,
        0,
        M::View,
    ),
    (
        E::ArbGasInfo,
        "getMinimumGasPrice",
        [0xf9, 0x18, 0x37, 0x9a],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbGasInfo,
        "getMultiGasBaseFee",
        [0xc0, 0xe1, 0x0b, 0xbb],
        0,
        60,
        0,
        M::View,
    ),
    (
        E::ArbGasInfo,
        "getMultiGasPricingConstraints",
        [0xbb, 0xfc, 0x0a, 0x72],
        0,
        60,
        0,
        M::View,
    ),
    (
        E::ArbGasInfo,
        "getPerBatchGasCharge",
        [0x6e, 0xcc, 0xa4, 0x5a],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbGasInfo,
        "getPricesInArbGas",
        [0x02, 0x19, 0x9f, 0x34],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbGasInfo,
        "getPricesInArbGasWithAggregator",
        [0x7a, 0x1e, 0xa7, 0x32],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbGasInfo,
        "getPricesInWei",
        [0x41, 0xb2, 0x47, 0xa8],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbGasInfo,
        "getPricesInWeiWithAggregator",
        [0xba, 0x9c, 0x91, 0x6e],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbGasInfo,
        "getPricingInertia",
        [0x3d, 0xfb, 0x45, 0xb9],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbInfo,
        "getBalance",
        [0xf8, 0xb2, 0xcb, 0x4f],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbInfo,
        "getCode",
        [0x7e, 0x10, 0x5c, 0xe2],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbNativeTokenManager,
        "burnNativeToken",
        [0x1c, 0x67, 0x9a, 0x3c],
        41,
        41,
        0,
        M::Write,
    ),
    (
        E::ArbNativeTokenManager,
        "mintNativeToken",
        [0xa6, 0xf0, 0xf7, 0xc7],
        41,
        41,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "addChainOwner",
        [0x48, 0x1f, 0x8d, 0xbf],
        0,
        0,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "addNativeTokenOwner",
        [0xae, 0xb3, 0xa4, 0x64],
        0,
        41,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "addTransactionFilterer",
        [0x59, 0xc8, 0x7a, 0xcc],
        0,
        60,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "addWasmCacheManager",
        [0xff, 0xdc, 0xa5, 0x15],
        0,
        30,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "getAllChainOwners",
        [0x51, 0x6b, 0x4e, 0x0f],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbOwner,
        "getAllNativeTokenOwners",
        [0x3f, 0x86, 0x01, 0xe4],
        0,
        41,
        0,
        M::View,
    ),
    (
        E::ArbOwner,
        "getAllTransactionFilterers",
        [0x59, 0x5f, 0xbb, 0x5a],
        0,
        60,
        0,
        M::View,
    ),
    (
        E::ArbOwner,
        "getFilteredFundsRecipient",
        [0x3c, 0xaa, 0x5f, 0x12],
        0,
        60,
        0,
        M::View,
    ),
    (
        E::ArbOwner,
        "getInfraFeeAccount",
        [0xee, 0x95, 0xa8, 0x24],
        0,
        5,
        0,
        M::View,
    ),
    (
        E::ArbOwner,
        "getNetworkFeeAccount",
        [0x2d, 0x91, 0x25, 0xe9],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbOwner,
        "isChainOwner",
        [0x26, 0xef, 0x7f, 0x68],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbOwner,
        "isNativeTokenOwner",
        [0xc6, 0x86, 0xf4, 0xdb],
        0,
        41,
        0,
        M::View,
    ),
    (
        E::ArbOwner,
        "isTransactionFilterer",
        [0xb3, 0x23, 0x52, 0xc3],
        0,
        60,
        0,
        M::View,
    ),
    (
        E::ArbOwner,
        "releaseL1PricerSurplusFunds",
        [0x31, 0x4b, 0xcf, 0x05],
        0,
        10,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "removeChainOwner",
        [0x87, 0x92, 0x70, 0x1a],
        0,
        0,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "removeNativeTokenOwner",
        [0x96, 0xa3, 0x75, 0x1d],
        0,
        41,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "removeTransactionFilterer",
        [0x67, 0xad, 0xa0, 0x89],
        0,
        60,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "removeWasmCacheManager",
        [0xbf, 0x19, 0x73, 0x22],
        0,
        30,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "scheduleArbOSUpgrade",
        [0xe3, 0x88, 0xb3, 0x81],
        0,
        0,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setAmortizedCostCapBips",
        [0x56, 0x19, 0x1c, 0xc3],
        0,
        0,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setBrotliCompressionLevel",
        [0x53, 0x99, 0x12, 0x6f],
        0,
        20,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setCalldataPriceIncrease",
        [0x8e, 0xb9, 0x11, 0xd9],
        0,
        40,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setChainConfig",
        [0xed, 0xa7, 0x32, 0x12],
        0,
        11,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setCollectTips",
        [0xa8, 0x58, 0xdb, 0xe2],
        0,
        60,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setFilteredFundsRecipient",
        [0xb7, 0x9d, 0xa0, 0xe9],
        0,
        60,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setGasBacklog",
        [0x68, 0xfc, 0x80, 0x8a],
        0,
        50,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setGasPricingConstraints",
        [0xcc, 0x0d, 0x55, 0x6a],
        0,
        50,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setInfraFeeAccount",
        [0x57, 0xf5, 0x85, 0xdb],
        0,
        5,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setInkPrice",
        [0x8c, 0x1d, 0x4f, 0xda],
        0,
        30,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setL1BaseFeeEstimateInertia",
        [0x71, 0x8f, 0x78, 0x05],
        0,
        0,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setL1PricePerUnit",
        [0x2b, 0x35, 0x2f, 0xae],
        0,
        0,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setL1PricingEquilibrationUnits",
        [0x15, 0x2d, 0xb6, 0x96],
        0,
        0,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setL1PricingInertia",
        [0x77, 0x5a, 0x82, 0xe9],
        0,
        0,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setL1PricingRewardRate",
        [0xf6, 0x73, 0x95, 0x00],
        0,
        0,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setL1PricingRewardRecipient",
        [0x93, 0x4b, 0xe0, 0x7d],
        0,
        0,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setL2BaseFee",
        [0xd9, 0x9b, 0xc8, 0x0e],
        0,
        0,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setL2GasBacklogTolerance",
        [0x19, 0x8e, 0x71, 0x57],
        0,
        0,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setL2GasPricingInertia",
        [0x3f, 0xd6, 0x2a, 0x29],
        0,
        0,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setMaxBlockGasLimit",
        [0xae, 0x10, 0x5c, 0x80],
        0,
        50,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setMaxStylusContractFragments",
        [0xf1, 0xfe, 0x1a, 0x70],
        0,
        60,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setMaxTxGasLimit",
        [0x39, 0x67, 0x36, 0x11],
        0,
        0,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setMinimumL2BaseFee",
        [0xa0, 0x18, 0x8c, 0xdb],
        0,
        0,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setMultiGasPricingConstraints",
        [0x2b, 0x05, 0xbb, 0x39],
        0,
        60,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setNativeTokenManagementFrom",
        [0xbd, 0xb8, 0xf7, 0x07],
        0,
        41,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setNetworkFeeAccount",
        [0xfc, 0xdd, 0xe2, 0xb4],
        0,
        0,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setParentGasFloorPerToken",
        [0x3a, 0x93, 0x0b, 0x0b],
        0,
        50,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setPerBatchGasCharge",
        [0xfa, 0xd7, 0xf2, 0x0b],
        0,
        0,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setSpeedLimit",
        [0x4d, 0x7a, 0x06, 0x0d],
        0,
        0,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setTransactionFilteringFrom",
        [0x46, 0x06, 0x6e, 0x45],
        0,
        60,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setWasmActivationGas",
        [0xa0, 0xa3, 0x24, 0x97],
        0,
        59,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setWasmBlockCacheSize",
        [0x38, 0x0f, 0x14, 0x57],
        0,
        30,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setWasmExpiryDays",
        [0xaa, 0xc6, 0x80, 0x18],
        0,
        30,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setWasmFreePages",
        [0x3f, 0x37, 0xa8, 0x46],
        0,
        30,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setWasmInitCostScalar",
        [0x67, 0xe0, 0x71, 0x8f],
        0,
        30,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setWasmKeepaliveDays",
        [0x2a, 0x9c, 0xbe, 0x3e],
        0,
        30,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setWasmMaxSize",
        [0x45, 0x5e, 0xc2, 0xeb],
        0,
        40,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setWasmMaxStackDepth",
        [0x45, 0x67, 0xcc, 0x8e],
        0,
        30,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setWasmMinInitGas",
        [0x82, 0x93, 0x40, 0x5e],
        0,
        30,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setWasmPageGas",
        [0xaa, 0xa6, 0x19, 0xe0],
        0,
        30,
        0,
        M::Write,
    ),
    (
        E::ArbOwner,
        "setWasmPageLimit",
        [0x65, 0x95, 0x38, 0x1a],
        0,
        30,
        0,
        M::Write,
    ),
    (
        E::ArbOwnerPublic,
        "getAllChainOwners",
        [0x51, 0x6b, 0x4e, 0x0f],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbOwnerPublic,
        "getAllNativeTokenOwners",
        [0x3f, 0x86, 0x01, 0xe4],
        0,
        41,
        0,
        M::View,
    ),
    (
        E::ArbOwnerPublic,
        "getAllTransactionFilterers",
        [0x59, 0x5f, 0xbb, 0x5a],
        0,
        60,
        0,
        M::View,
    ),
    (
        E::ArbOwnerPublic,
        "getBrotliCompressionLevel",
        [0x22, 0xd4, 0x99, 0xc7],
        0,
        20,
        0,
        M::View,
    ),
    (
        E::ArbOwnerPublic,
        "getCollectTips",
        [0x8e, 0x34, 0xa6, 0x4d],
        0,
        60,
        0,
        M::View,
    ),
    (
        E::ArbOwnerPublic,
        "getFilteredFundsRecipient",
        [0x3c, 0xaa, 0x5f, 0x12],
        0,
        60,
        0,
        M::View,
    ),
    (
        E::ArbOwnerPublic,
        "getInfraFeeAccount",
        [0xee, 0x95, 0xa8, 0x24],
        0,
        5,
        0,
        M::View,
    ),
    (
        E::ArbOwnerPublic,
        "getMaxStylusContractFragments",
        [0xe5, 0xa7, 0xf8, 0x93],
        0,
        60,
        0,
        M::View,
    ),
    (
        E::ArbOwnerPublic,
        "getNativeTokenManagementFrom",
        [0x3f, 0xec, 0xba, 0xb0],
        0,
        50,
        0,
        M::View,
    ),
    (
        E::ArbOwnerPublic,
        "getNetworkFeeAccount",
        [0x2d, 0x91, 0x25, 0xe9],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbOwnerPublic,
        "getParentGasFloorPerToken",
        [0x49, 0xcc, 0xda, 0xff],
        0,
        50,
        0,
        M::View,
    ),
    (
        E::ArbOwnerPublic,
        "getScheduledUpgrade",
        [0x81, 0xef, 0x94, 0x4c],
        0,
        20,
        0,
        M::View,
    ),
    (
        E::ArbOwnerPublic,
        "getTransactionFilteringFrom",
        [0xc1, 0xd3, 0x55, 0xb8],
        0,
        60,
        0,
        M::View,
    ),
    (
        E::ArbOwnerPublic,
        "isCalldataPriceIncreaseEnabled",
        [0x2a, 0xa9, 0x55, 0x1e],
        0,
        40,
        0,
        M::View,
    ),
    (
        E::ArbOwnerPublic,
        "isChainOwner",
        [0x26, 0xef, 0x7f, 0x68],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbOwnerPublic,
        "isNativeTokenOwner",
        [0xc6, 0x86, 0xf4, 0xdb],
        0,
        41,
        0,
        M::View,
    ),
    (
        E::ArbOwnerPublic,
        "isTransactionFilterer",
        [0xb3, 0x23, 0x52, 0xc3],
        0,
        60,
        0,
        M::View,
    ),
    (
        E::ArbOwnerPublic,
        "rectifyChainOwner",
        [0x6f, 0xe8, 0x63, 0x73],
        0,
        11,
        0,
        M::Write,
    ),
    (
        E::ArbRetryableTx,
        "cancel",
        [0xc4, 0xd2, 0x52, 0xf5],
        0,
        0,
        0,
        M::Write,
    ),
    (
        E::ArbRetryableTx,
        "getBeneficiary",
        [0xba, 0x20, 0xdd, 0xa4],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbRetryableTx,
        "getCurrentRedeemer",
        [0xde, 0x4b, 0xa2, 0xb3],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbRetryableTx,
        "getLifetime",
        [0x81, 0xe6, 0xe0, 0x83],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbRetryableTx,
        "getTimeout",
        [0x9f, 0x10, 0x25, 0xc6],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbRetryableTx,
        "keepalive",
        [0xf0, 0xb2, 0x1a, 0x41],
        0,
        0,
        0,
        M::Write,
    ),
    (
        E::ArbRetryableTx,
        "redeem",
        [0xed, 0xa1, 0x12, 0x2c],
        0,
        0,
        0,
        M::Write,
    ),
    (
        E::ArbRetryableTx,
        "submitRetryable",
        [0xc9, 0xf9, 0x5d, 0x32],
        0,
        0,
        0,
        M::Write,
    ),
    (
        E::ArbStatistics,
        "getStats",
        [0xc5, 0x9d, 0x48, 0x47],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbSys,
        "arbBlockHash",
        [0x2b, 0x40, 0x7a, 0x82],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbSys,
        "arbBlockNumber",
        [0xa3, 0xb1, 0xb3, 0x1d],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbSys,
        "arbChainID",
        [0xd1, 0x27, 0xf5, 0x4a],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbSys,
        "arbOSVersion",
        [0x05, 0x10, 0x38, 0xf2],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbSys,
        "getStorageGasAvailable",
        [0xa9, 0x45, 0x97, 0xff],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbSys,
        "isTopLevelCall",
        [0x08, 0xbd, 0x62, 0x4c],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbSys,
        "mapL1SenderContractAddressToL2Alias",
        [0x4d, 0xbb, 0xd5, 0x06],
        0,
        0,
        0,
        M::Pure,
    ),
    (
        E::ArbSys,
        "myCallersAddressWithoutAliasing",
        [0xd7, 0x45, 0x23, 0xb3],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbSys,
        "sendMerkleTreeState",
        [0x7a, 0xee, 0xcd, 0x2a],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbSys,
        "sendTxToL1",
        [0x92, 0x8c, 0x16, 0x9a],
        0,
        0,
        0,
        M::Payable,
    ),
    (
        E::ArbSys,
        "wasMyCallersAddressAliased",
        [0x17, 0x5a, 0x26, 0x0b],
        0,
        0,
        0,
        M::View,
    ),
    (
        E::ArbSys,
        "withdrawEth",
        [0x25, 0xe1, 0x60, 0x63],
        0,
        0,
        0,
        M::Payable,
    ),
    (
        E::ArbWasm,
        "activateProgram",
        [0x58, 0xc7, 0x80, 0xc2],
        30,
        30,
        0,
        M::Payable,
    ),
    (
        E::ArbWasm,
        "activationGas",
        [0x22, 0x78, 0xc2, 0x78],
        30,
        59,
        0,
        M::View,
    ),
    (
        E::ArbWasm,
        "blockCacheSize",
        [0x7a, 0xf6, 0xe8, 0x19],
        30,
        30,
        0,
        M::View,
    ),
    (
        E::ArbWasm,
        "codehashAsmSize",
        [0x40, 0x89, 0x26, 0x7f],
        30,
        30,
        0,
        M::View,
    ),
    (
        E::ArbWasm,
        "codehashKeepalive",
        [0xc6, 0x89, 0xba, 0xd5],
        30,
        30,
        0,
        M::Payable,
    ),
    (
        E::ArbWasm,
        "codehashVersion",
        [0xd7, 0x0c, 0x0c, 0xa7],
        30,
        30,
        0,
        M::View,
    ),
    (
        E::ArbWasm,
        "expiryDays",
        [0x30, 0x9f, 0x65, 0x55],
        30,
        30,
        0,
        M::View,
    ),
    (
        E::ArbWasm,
        "freePages",
        [0x44, 0x90, 0xc1, 0x9d],
        30,
        30,
        0,
        M::View,
    ),
    (
        E::ArbWasm,
        "initCostScalar",
        [0x5f, 0xc9, 0x4c, 0x0b],
        30,
        30,
        0,
        M::View,
    ),
    (
        E::ArbWasm,
        "inkPrice",
        [0xd1, 0xc1, 0x7a, 0xbc],
        30,
        30,
        0,
        M::View,
    ),
    (
        E::ArbWasm,
        "keepaliveDays",
        [0x0a, 0x93, 0x64, 0x55],
        30,
        30,
        0,
        M::View,
    ),
    (
        E::ArbWasm,
        "maxStackDepth",
        [0x8c, 0xcf, 0xaa, 0x70],
        30,
        30,
        0,
        M::View,
    ),
    (
        E::ArbWasm,
        "minInitGas",
        [0x99, 0xd0, 0xb3, 0x8d],
        30,
        30,
        0,
        M::View,
    ),
    (
        E::ArbWasm,
        "pageGas",
        [0x7a, 0xf4, 0xba, 0x49],
        30,
        30,
        0,
        M::View,
    ),
    (
        E::ArbWasm,
        "pageLimit",
        [0x97, 0x86, 0xf9, 0x6e],
        30,
        30,
        0,
        M::View,
    ),
    (
        E::ArbWasm,
        "pageRamp",
        [0x11, 0xc8, 0x2a, 0xe8],
        30,
        30,
        0,
        M::View,
    ),
    (
        E::ArbWasm,
        "programInitGas",
        [0x62, 0xb6, 0x88, 0xaa],
        30,
        30,
        0,
        M::View,
    ),
    (
        E::ArbWasm,
        "programMemoryFootprint",
        [0xae, 0xf3, 0x6b, 0xe3],
        30,
        30,
        0,
        M::View,
    ),
    (
        E::ArbWasm,
        "programTimeLeft",
        [0xc7, 0x75, 0xa6, 0x2a],
        30,
        30,
        0,
        M::View,
    ),
    (
        E::ArbWasm,
        "programVersion",
        [0xcc, 0x8f, 0x4e, 0x88],
        30,
        30,
        0,
        M::View,
    ),
    (
        E::ArbWasm,
        "stylusVersion",
        [0xa9, 0x96, 0xe0, 0xc2],
        30,
        30,
        0,
        M::View,
    ),
    (
        E::ArbWasmCache,
        "allCacheManagers",
        [0x0e, 0xc1, 0xd7, 0x73],
        30,
        30,
        0,
        M::View,
    ),
    (
        E::ArbWasmCache,
        "cacheCodehash",
        [0x4c, 0xea, 0xc8, 0x17],
        30,
        30,
        30,
        M::Write,
    ),
    (
        E::ArbWasmCache,
        "cacheProgram",
        [0xe7, 0x3a, 0xc9, 0xf2],
        30,
        31,
        0,
        M::Write,
    ),
    (
        E::ArbWasmCache,
        "codehashIsCached",
        [0xa7, 0x2f, 0x17, 0x9b],
        30,
        30,
        0,
        M::View,
    ),
    (
        E::ArbWasmCache,
        "evictCodehash",
        [0xce, 0x97, 0x20, 0x13],
        30,
        30,
        0,
        M::Write,
    ),
    (
        E::ArbWasmCache,
        "isCacheManager",
        [0x85, 0xe2, 0xde, 0x85],
        30,
        30,
        0,
        M::View,
    ),
    (
        E::ArbosActs,
        "batchPostingReport",
        [0xb6, 0x69, 0x37, 0x71],
        0,
        0,
        0,
        M::Write,
    ),
    (
        E::ArbosActs,
        "batchPostingReportV2",
        [0x99, 0x98, 0x26, 0x9e],
        0,
        0,
        0,
        M::Write,
    ),
    (
        E::ArbosActs,
        "startBlock",
        [0x6b, 0xf6, 0xa4, 0x2d],
        0,
        0,
        0,
        M::Write,
    ),
    (
        E::ArbosTest,
        "burnArbGas",
        [0xbb, 0x34, 0x80, 0xf9],
        0,
        0,
        0,
        M::Pure,
    ),
];
